services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-hub
    restart: unless-stopped
    ports:
      - "7474:7474" # Painel Administrativo Web (HTTP)
      - "7687:7687" # Protocolo Bolt (Conexão nativa do Spring)
    environment:
      - NEO4J_AUTH=neo4j/senha123
      # Otimização recomendada para desenvolvimento local
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_initial__size=512M
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  neo4j_data:
  neo4j_logs: