spring:
  application:
    name: hub-entretenimento
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.1-flash-lite
            temperature: 0.4